
stages:
  - images
  - build
  - test

image_linux:
    stage: images
    tags:
        - linux
    image:
        name: docker:20.10
    services:
        - docker:20.10-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - mkdir -p $HOME/.docker
        - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    script:
        - docker build -t linux/builder images/linux
        - docker tag linux/builder registry.gams.com/devel/gams-transfer-matlab/linux/builder:latest
        - docker push registry.gams.com/devel/gams-transfer-matlab/linux/builder:latest
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            - images/linux/Dockerfile
          when: manual
          allow_failure: true

build_octave_linux:
    stage: build
    tags :
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-matlab/linux/builder
    script:
        - octave --no-gui --no-window-system --eval "gams_transfer_setup('target_dir', 'linux')"
    only:
        - merge_requests
        - master
    artifacts:
        paths:
            - linux
        expire_in: 1 day

build_octave_macos:
    stage: build
    tags :
        - macos
    script:
        - octave --no-gui --no-window-system --eval "gams_transfer_setup('target_dir', 'macos')"
    only:
        - merge_requests
        - master
    artifacts:
        paths:
            - macos
        expire_in: 1 day

test_octave_linux:
    stage: test
    tags :
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-matlab/linux/builder
    script:
        - octave --no-gui --no-window-system --path $PWD/linux --eval "gams_transfer_test('gams_dir', '/opt/gams', 'working_dir', 'test', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master

test_octave_macos:
    stage: test
    tags :
        - macos
    script:
        - octave --no-gui --no-window-system --path $PWD/macos --eval "gams_transfer_test('gams_dir', '/opt/gams', 'working_dir', 'test', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master