
stages:
  - images
  - doc
  - download
  - octave:build
  - octave:test
  - matlab:build
  - matlab:test
  - package
  - release
  - deploy

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gams_transfer_matlab/${CI_COMMIT_TAG}/"

image_linux:
    stage: images
    tags:
        - linux
    image:
        name: docker:20.10
    services:
        - docker:20.10-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - mkdir -p $HOME/.docker
        - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    script:
        - sed -i "s/_matlab_username_/$MATLAB_USERNAME/g" images/linux/runmatlab.sh
        - sed -i "s/_matlab_password_/$MATLAB_PASSWORD/g" images/linux/runmatlab.sh
        - docker build -t linux/builder images/linux
        - docker tag linux/builder $CI_REGISTRY_IMAGE/linux/builder:latest
        - docker push $CI_REGISTRY_IMAGE/linux/builder:latest
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            - images/linux/Dockerfile
          when: manual
          allow_failure: true

doc:build:
    stage: doc
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    needs: []
    script:
        - mkdir -p build
        - doxygen doc/Doxyfile
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: doc
        paths:
            - build/doc/html
        expire_in: 10 min

download:linux:
    stage: download
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    needs: []
    script:
        - mkdir -p linux/gdx
        - curl -o gdx.zip $URL_GDX_LINUX
        - unzip gdx.zip -d linux/gdx
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: linux:gdx
        paths:
            - linux/gdx
        expire_in: 10 min

download:macos:
    stage: download
    tags:
        - macos
    needs: []
    script:
        - mkdir -p macos/gdx
        - curl -o gdx.zip $URL_GDX_MACOS
        - tar -xf gdx.zip -C macos/gdx
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: macos:gdx
        paths:
            - macos/gdx
        expire_in: 10 min

download:macos_arm:
    stage: download
    tags:
        - macos-arm64
    needs: []
    script:
        - mkdir -p macos_arm/gdx
        - curl -o gdx.zip $URL_GDX_MACOS_ARM
        - tar -xf gdx.zip -C macos_arm/gdx
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: macos_arm:gdx
        paths:
            - macos_arm/gdx
        expire_in: 10 min

download:windows:
    stage: download
    tags:
        - windows-shell
    needs: []
    script:
        - mkdir -p windows/gdx
        - curl -o gdx.zip $URL_GDX_WINDOWS
        - tar -xf gdx.zip -C windows/gdx
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: windows:gdx
        paths:
            - windows/gdx
        expire_in: 10 min

octave:build:linux:
    stage: octave:build
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    needs: [download:linux]
    script:
        - mkdir -p linux/octave
        - cp -r +gams linux/octave
        - cd linux/octave
        - octave --no-gui --no-window-system --eval "gams.transfer.setup('gams_dir', '../gdx', 'verbose', $BUILD_VERBOSITY)"
    only:
        - merge_requests
        - master
    artifacts:
        name: linux:octave
        paths:
            - linux/octave/+gams
        expire_in: 10 min

octave:build:macos:
    stage: octave:build
    tags:
        - macos
    needs: [download:macos]
    script:
        - mkdir -p macos/octave
        - cp -r +gams macos/octave
        - cd macos/octave
        - octave --no-gui --no-window-system --eval "gams.transfer.setup('gams_dir', '../gdx', 'verbose', $BUILD_VERBOSITY)"
    only:
        - merge_requests
        - master
    artifacts:
        name: macos:octave
        paths:
            - macos/octave/+gams
        expire_in: 10 min

octave:build:macos_arm:
    stage: octave:build
    tags:
        - macos-arm64
    needs: [download:macos_arm]
    script:
        - mkdir -p macos_arm/octave
        - cp -r +gams macos_arm/octave
        - cd macos_arm/octave
        - octave --no-gui --no-window-system --eval "gams.transfer.setup('gams_dir', '../gdx', 'verbose', $BUILD_VERBOSITY)"
    only:
        - merge_requests
        - master
    artifacts:
        name: macos_arm:octave
        paths:
            - macos_arm/octave/+gams
        expire_in: 10 min

matlab:build:linux:
    stage: matlab:build
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    needs: [download:linux]
    script:
        - mkdir -p linux/matlab
        - cp -r +gams linux/matlab
        - cd linux/matlab
        - ~/Documents/MATLAB/runmatlab.sh "gams.transfer.setup('gams_dir', '../gdx', 'verbose', $BUILD_VERBOSITY)"
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: linux:matlab
        paths:
            - linux/matlab/+gams
        expire_in: 10 min

matlab:build:macos:
    stage: matlab:build
    tags:
        - macos
    needs: [download:macos]
    script:
        - mkdir -p macos/matlab
        - cp -r +gams macos/matlab
        - cd macos/matlab
        - matlab -nodisplay -nosplash -nodesktop -r "gams.transfer.setup('gams_dir', '../gdx', 'verbose', $BUILD_VERBOSITY)"
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: macos:matlab
        paths:
            - macos/matlab/+gams
        expire_in: 10 min

matlab:build:macos_arm:
    stage: matlab:build
    tags:
        - macos-arm64
    needs: [download:macos_arm]
    script:
        - mkdir -p macos_arm/matlab
        - cp -r +gams macos_arm/matlab
        - cd macos_arm/matlab
        - matlab -nodisplay -nosplash -nodesktop -r "gams.transfer.setup('gams_dir', '../gdx', 'verbose', $BUILD_VERBOSITY)"
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: macos_arm:matlab
        paths:
            - macos_arm/matlab/+gams
        expire_in: 10 min

matlab:build:windows:
    stage: matlab:build
    tags:
        - windows-shell
    needs: [download:windows]
    script:
        - mkdir -p windows/matlab
        - cp -r +gams windows/matlab
        - cd windows/matlab
        - matlab.exe -batch "gams.transfer.setup('gams_dir', '../gdx', 'verbose', $BUILD_VERBOSITY)"
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: windows:matlab
        paths:
            - windows/matlab/+gams
        expire_in: 10 min

octave:test:linux:
    stage: octave:test
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    needs: [download:linux, octave:build:linux]
    script:
        - octave --no-gui --no-window-system --path $PWD/test --eval "run_tests('linux/octave', 'gams_dir', 'linux/gdx', 'working_dir', 'unittest', 'exit_on_fail', true, 'only_default_config', true)"
    only:
        - merge_requests
        - master

octave:test:macos:
    stage: octave:test
    tags:
        - macos
    needs: [download:macos, octave:build:macos]
    script:
        - octave --no-gui --no-window-system --path $PWD/test --eval "run_tests('macos/octave', 'gams_dir', 'macos/gdx', 'working_dir', 'unittest', 'exit_on_fail', true, 'only_default_config', true)"
    only:
        - merge_requests
        - master

octave:test:macos_arm:
    stage: octave:test
    tags:
        - macos-arm64
    needs: [download:macos_arm, octave:build:macos_arm]
    script:
        - octave --no-gui --no-window-system --path $PWD/test --eval "run_tests('macos_arm/octave', 'gams_dir', 'macos_arm/gdx', 'working_dir', 'unittest', 'exit_on_fail', true, 'only_default_config', true)"
    only:
        - merge_requests
        - master

matlab:test:linux:
    stage: matlab:test
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    needs: [download:linux, matlab:build:linux]
    script:
        - ~/Documents/MATLAB/runmatlab.sh "addpath('test'); run_tests('linux/matlab', 'gams_dir', 'linux/gdx', 'working_dir', 'unittest', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master

matlab:test:macos:
    stage: matlab:test
    tags:
        - macos
    needs: [download:macos, matlab:build:macos]
    script:
        - matlab -batch "addpath('test'); run_tests('macos/matlab', 'gams_dir', 'macos/gdx', 'working_dir', 'unittest', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master

matlab:test:macos_arm:
    stage: matlab:test
    tags:
        - macos-arm64
    needs: [download:macos_arm, matlab:build:macos_arm]
    script:
        - matlab -batch "addpath('test'); run_tests('macos_arm/matlab', 'gams_dir', 'macos_arm/gdx', 'working_dir', 'unittest', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master

matlab:test:windows:
    stage: matlab:test
    tags:
        - windows-shell
    needs: [download:windows, matlab:build:windows]
    script:
        - matlab.exe -batch "addpath('test'); run_tests('windows/matlab', 'gams_dir', 'windows/gdx', 'working_dir', 'unittest', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master

package:
    stage: package
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    script:
        - cd linux/matlab
        - sudo zip -r gams_transfer_matlab_linux.zip +gams
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gams_transfer_matlab_linux.zip ${PACKAGE_REGISTRY_URL}
        - cd ../../macos/matlab
        - sudo zip -r gams_transfer_matlab_macos.zip +gams
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gams_transfer_matlab_macos.zip ${PACKAGE_REGISTRY_URL}
        - cd ../../macos_arm/matlab
        - sudo zip -r gams_transfer_matlab_macos_arm.zip +gams
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gams_transfer_matlab_macos_arm.zip ${PACKAGE_REGISTRY_URL}
        - cd ../../windows/matlab
        - sudo zip -r gams_transfer_matlab_windows.zip +gams
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gams_transfer_matlab_windows.zip ${PACKAGE_REGISTRY_URL}
    only:
        - tags

release:
    stage: release
    tags:
        - linux
    image:
        name: $CI_REGISTRY_IMAGE/linux/builder
    script:
        - DESCR=$(grep -Pzo "(?s)GAMS Transfer Matlab $CI_COMMIT_TAG.*?((?=\nGAMS Transfer Matlab v)|$)" CHANGELOG.md | tr -d '\0')
        - |
            release-cli create \
                --name "Release $CI_COMMIT_TAG" \
                --tag-name $CI_COMMIT_TAG \
                --description "$DESCR" \
                --assets-link "{\"name\":\"gams_transfer_matlab_linux.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gams_transfer_matlab_linux.zip\"}" \
                --assets-link "{\"name\":\"gams_transfer_matlab_macos.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gams_transfer_matlab_macos.zip\"}" \
                --assets-link "{\"name\":\"gams_transfer_matlab_macos_arm.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gams_transfer_matlab_macos_arm.zip\"}" \
                --assets-link "{\"name\":\"gams_transfer_matlab_windows.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gams_transfer_matlab_windows.zip\"}"
    only:
        - tags

pages:
    stage: deploy
    tags:
        - linux
    image:
        name: alpine
    script:
        - mv build/doc/html public/
    artifacts:
        paths:
            - public
    only:
        - master
        - tags
