
stages:
  - images
  - build
  - test
  - package
  - release
  - deploy

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gams_transfer_matlab/${CI_COMMIT_TAG}/"

image_linux:
    stage: images
    tags:
        - linux
    image:
        name: docker:20.10
    services:
        - docker:20.10-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - mkdir -p $HOME/.docker
        - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    script:
        - docker build -t linux/builder images/linux
        - docker tag linux/builder registry.gams.com/devel/gams-transfer-matlab/linux/builder:latest
        - docker push registry.gams.com/devel/gams-transfer-matlab/linux/builder:latest
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            - images/linux/Dockerfile
          when: manual
          allow_failure: true

build_documentation:
    stage: build
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-matlab/linux/builder
    script:
        - ./gams_transfer_doc.sh
    only:
        - merge_requests
        - master
    artifacts:
        name: doc
        paths:
            - doc/html
        expire_in: 1 day

build_octave_linux:
    stage: build
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-matlab/linux/builder
    script:
        - octave --no-gui --no-window-system --eval "gams_transfer_setup('target_dir', 'octave_linux')"
    only:
        - merge_requests
        - master
    artifacts:
        name: gams_transfer_octave_linux
        paths:
            - octave_linux
        expire_in: 1 day

build_octave_macos:
    stage: build
    tags:
        - macos
    script:
        - octave --no-gui --no-window-system --eval "gams_transfer_setup('target_dir', 'octave_macos')"
    only:
        - merge_requests
        - master
    artifacts:
        name: gams_transfer_octave_macos
        paths:
            - octave_macos
        expire_in: 1 day

build_matlab_macos:
    stage: build
    tags:
        - macos
    script:
        - matlab -nodisplay -nosplash -nodesktop -r "gams_transfer_setup('target_dir', 'matlab_macos')"
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: gams_transfer_matlab_macos
        paths:
            - matlab_macos
        expire_in: 1 day

build_matlab_windows:
    stage: build
    tags:
        - windows-shell
    script:
        - C:\"Program Files"\MATLAB\bin\matlab.exe -batch "gams_transfer_setup('target_dir', 'matlab_windows')"
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: gams_transfer_matlab_windows
        paths:
            - matlab_windows
        expire_in: 1 day

test_octave_linux:
    stage: test
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-matlab/linux/builder
    needs: [build_octave_linux]
    script:
        - ls /opt/gams29.1.0
        - octave --no-gui --no-window-system --path $PWD/octave_linux --eval "gams_transfer_test('gams_dir', '/opt/gams29.1.0', 'working_dir', 'unittest', 'exit_on_fail', true, 'only_default_config', true)"
    only:
        - merge_requests
        - master

test_octave_macos:
    stage: test
    tags:
        - macos
    needs: [build_octave_macos]
    script:
        - octave --no-gui --no-window-system --path $PWD/octave_macos --eval "gams_transfer_test('gams_dir', '/opt/gams', 'working_dir', 'unittest', 'exit_on_fail', true, 'only_default_config', true)"
    only:
        - merge_requests
        - master

test_matlab_macos:
    stage: test
    tags:
        - macos
    needs: [build_matlab_macos]
    script:
        - matlab -nodisplay -nosplash -nodesktop -r "addpath('matlab_macos'); gams_transfer_test('gams_dir', '/opt/gams', 'working_dir', 'unittest', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master

test_matlab_windows:
    stage: test
    tags:
        - windows-shell
    needs: [build_matlab_windows]
    script:
        - mkdir gdx
        - cd gdx
        - curl -o gdx.zip https://cloud.gams.com/s/wQKgjWkExkbPqNs/download/gamstransfer_gdx_windows.zip
        - tar -xf gdx.zip
        - cd ..
        - C:\"Program Files"\MATLAB\bin\matlab.exe -batch "addpath('matlab_windows'); gams_transfer_test('gams_dir', 'gdx', 'working_dir', 'unittest', 'exit_on_fail', true)"
    only:
        - merge_requests
        - master

package:
    stage: package
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-matlab/linux/builder
    script:
        - cd matlab_macos
        - zip -r gams_transfer_matlab_macos.zip +GAMSTransfer
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gams_transfer_matlab_macos.zip ${PACKAGE_REGISTRY_URL}
        - cd ..
        - cd matlab_windows
        - zip -r gams_transfer_matlab_windows.zip +GAMSTransfer
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gams_transfer_matlab_windows.zip ${PACKAGE_REGISTRY_URL}
    only:
        - tags

release:
    stage: release
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-matlab/linux/builder
    script:
        - DESCR=$(grep -Pzo "(?s)GAMS Transfer Matlab $CI_COMMIT_TAG.*?((?=\nGAMS Transfer Matlab v)|$)" CHANGELOG | tr -d '\0')
        - |
            release-cli create \
                --name "Release $CI_COMMIT_TAG" \
                --tag-name $CI_COMMIT_TAG \
                --description "$DESCR" \
                --assets-link "{\"name\":\"gams_transfer_matlab_macos.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gams_transfer_matlab_macos.zip\"}" \
                --assets-link "{\"name\":\"gams_transfer_matlab_windows.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gams_transfer_matlab_windows.zip\"}"
    only:
        - tags

pages:
    stage: deploy
    tags:
        - linux
    image:
        name: alpine
    script:
        - mv doc/html public/
    artifacts:
        paths:
            - public
    only:
        - master
